app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('note.urls')),
    
]

note/urls.py
from django.urls import path

from . import views 
from .views import CustomLoginView, SignUpView
from django.contrib.auth.views import LogoutView

app_name = 'note'
urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page = 'note:login'), name='logout'),
    # path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup/',SignUpView.as_view(), name='signup'),
    # path('register/',RegisterPage.as_view(), name='register'),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name = 'delete'),
]

note/models.py
from django.db import models
from django.contrib.auth.models import User
class NotesModel(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE, null= True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
        

note/views.py
from rest_framework import viewsets

# import local data
from .serializer import NotesSerializer
from .models import NotesModel
from django.contrib.auth.views import LoginView
from django.views import generic
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


class CustomLoginView(LoginView):
	template_name = 'note/login.html'
	fields = ['user','title', 'description']
	redirect_authenticated_user = True

	def get_success_url(self):
		return reverse_lazy('note:index')

# class SignUpView(generic.CreateView):
#     form_class = UserCreationForm
#     success_url = reverse_lazy('note:index')
#     template_name = 'note/signup.html'
class SignUpView(FormView):
	template_name = 'note/signup.html'
	form_class = UserCreationForm
	redirect_authenticated_user = True
	success_url=reverse_lazy('note:index')

	def form_valid(self, form):
		user = form.save()
		if user is not None:
			login(self.request, user)
		return super(SignUpView, self).form_valid(form)



# class CustomLogoutView(LoginView):
# 	template_name = 'note/login.html'
# 	fields = ['user','title', 'description']
# 	redirect_authenticated_user = True

# 	def get_success_url(self):
# 		return reverse_lazy('note:index')


class IndexView(LoginRequiredMixin,generic.ListView):
	queryset = NotesModel.objects.all()
	template_name = 'note/index.html'

	
	# specify serializer to be used
	serializer_class = NotesSerializer

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['object_list'] = context['object_list'].filter(user = self.request.user)
		return context

class DetailView(LoginRequiredMixin,generic.DetailView):
	queryset = NotesModel.objects.all()
	fields = ['title', 'description']
	template_name = 'note/detail.html'

class CreateView(LoginRequiredMixin,generic.CreateView):
	queryset = NotesModel.objects.all()
	fields = ['user','title', 'description']
	success_url=reverse_lazy('note:index')
	template_name = 'note/create.html'

class UpdateView(LoginRequiredMixin,generic.UpdateView):
	queryset = NotesModel.objects.all()
	fields = ['user','title', 'description']
	success_url=reverse_lazy('note:index')
	template_name = 'note/update.html'

class DeleteView(LoginRequiredMixin,generic.DeleteView):
	queryset = NotesModel.objects.all()
	# success_url=reverse_lazy('note:index')
	template_name = 'note/delete.html'

note/templates/note/create.html
<body style="background-color:peachpuff;"></body>
<a href = "{% url 'note:index' %}">Go Back</a>
<form method="POST" enctype="multipart/form-data">

	<!-- Security token -->
	{% csrf_token %}

	<!-- Using the formset -->
	{{ form.as_p }}
	
	<input type="submit" value="Submit">
</form>

note/templates/note/delete.html
<body style="background-color:peachpuff;"></body>

<a href = "{% url 'note:index' %}">Go Back</a>
<form method="post">{% csrf_token %}
	

    <p>Are you sure you want to delete "{{ object }}"?</p>
    
    
        <input type="submit" value="Confirm">
    </form>
    

note/templates/note/detail.html
<body style="background-color:peachpuff;"></body>

<h1>Note: {{object}}</h1>

<h2>Description:</h2>
<p style="color:blue";><i>{{object.description}}</i></p>

note/templates/note/index.html
<html>
<style>
    body {
      background-color:peachpuff;
    
    }
</style>

<body>


{% if request.user.is_authenticated %}
<p>Hello {{request.user}}</p> 


<a href = "{% url 'note:logout' %}">Logout</a>
{% else %}
<!-- <p>You are not logged in</p> -->
<a href = "{% url 'note:login' %}">Login</a>
{% endif %}

<hr>
  
<h1>My notes</h1>
<a href = "{% url 'note:create' %}">Add a note</a>
<br>
<br>
<input id='myInput' onkeyup='searchTable()' type='text' placeholder="Search for a note.." title="Type in a note">

<table id='myTable'>
    <tr>
        <th>Notes</th>
    </tr>
    {% for NotesModel in object_list %}
    <tr>
        <td>{{ NotesModel.title }}</td>
        <td><a href = "{% url 'note:detail' NotesModel.id %}">View</a></td>
        <td><a href = "{% url 'note:update' NotesModel.id %}">Update</a></td>
        <td><a href = "{% url 'note:delete' NotesModel.id %}">Delete</a></td>
    </tr>
    {% empty %}
        <h3>No item</h3>
    {% endfor %}
</table>
   

<script>
function searchTable() {
    var input, filter, found, table, tr, td, i, j, txtValue;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    table = document.getElementById("myTable");
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td");
        for (j = 0; j < td.length; j++) {
            if (td[j].innerHTML.toUpperCase().indexOf(filter) > -1) {
                found = true;
            }
        }
        if (found) {
            tr[i].style.display = "";
            found = false;
        } else {
            tr[i].style.display = "none";
        }
    }
}
</script>


</body>
</html>

note/templates/note/login.html
<h1>Login</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type = "submit" value= "Login">
</form>

<p>Don't have a account? <a href = "{% url 'note:signup' %}">Signup</a></p> -->

note/templates/note/main.html
<!DOCTYPE html>

note/templates/note/rough.html
<table>
    <tr>
        <th>Description</th>
    </tr>
    {% for description in object.description %}
        <td>{{ description }}</td>
    
    {% empty %}
        <h3>No descrription</h3>
    {% endfor %}
</table>

<p>{{object.description}}</p>



for (j = 0; j < td.length; j++) {
    if (td[j].innerHTML.toUpperCase().indexOf(filter) > -1) {
        found = true;
    }
}
if (found) {
    tr[i].style.display = "";
    found = false;
} else {
    tr[i].style.display = "none";
}



<ul>
    {% for description in object.description %}
        <li> {{ description }} </li>
        <br>
    {% empty %}
        <h3>No descrription</h3>
    {% endfor %}

</ul>  

note/templates/note/signup.html
<h1>Signup</h1>
<form method="post">{% csrf_token %}
  {% csrf_token %}
  {{ form.as_p }}
  <input type = "submit" value= "Signup">
</form>

<p>Already have an account? <a href = "{% url 'note:login' %}">Login</a></p>

note/templates/note/update.html
<body style="background-color:peachpuff;"></body>

<a href = "{% url 'note:index' %}">Go Back</a>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>